theme = "everforest_dark"
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
line-number = "relative"

[editor.whitespace]
render = "all"
# or control each character

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
